### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()J

### ISSUE THREAD

**Issue by qshian** [metarank/lightgbm4j#46] opened 2021-05-12 02:51 UTC
when run :: 
public class TestCase {
    public static void main(String[] args) throws LGBMException {

        LGBMBooster booster = LGBMBooster.loadModelFromString("/Users/xx/Downloads/20210505_uid.lgb_180");
        float[] input = new float[] {1.0f, 1.0f, 1.0f, 1.0f};
        double[] pred = booster.predictForMat(input, 2, 2, true);
    }
}

then 

Loading native lib osx/x86_64/lib_lightgbm.dylib
Loading native lib /var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin
Copied 132 bytes
Extracted file: exists=true path=/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin
Cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: dlopen(/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin, 1): no suitable image found.  Did find:
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: file too short
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: file too short cause: /private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: dlopen(/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin, 1): no suitable image found.  Did find:
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: file too short
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_216735099292679332.bin: file too short
Loading native lib osx/x86_64/lib_lightgbm_swig.dylib
Loading native lib /var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin
Copied 130 bytes
Extracted file: exists=true path=/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin
Cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: dlopen(/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin, 1): no suitable image found.  Did find:
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: file too short
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: file too short cause: /private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: dlopen(/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin, 1): no suitable image found.  Did find:
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: file too short
	/private/var/folders/v3/nkjrtcfd6px1w3rg3l7g8h2c0000gq/T/lightgbm_swig_2701630091356538392.bin: file too short
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()J
	at com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp(Native Method)
	at com.microsoft.ml.lightgbm.lightgbmlib.new_voidpp(lightgbmlib.java:588)
	at io.github.metarank.lightgbm4j.LGBMBooster.loadModelFromString(LGBMBooster.java:130)
	at io.github.metarank.lightgbm4j.TestCase.main(TestCase.java:9)

**Comment by shuttie** [comment] 2021-06-01 11:41
Are you using the build from maven-central? As it looks like that the native libraries packed in the jar are not really there.
We use git-lfs to store the dll/so/dylib files in the repo, so if you did a custom build, make sure that you correctly fetched the LFS files.

**Comment by shuttie** [comment] 2021-06-01 11:42
You can try running these commands prior to building the JAR:
```
$ git lfs installl
$ git lfs pull
```

**Comment by NBXQ** [comment] 2021-11-24 13:21
i have the same situation:
Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()J
	at com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp(Native Method) 
	at com.microsoft.ml.lightgbm.lightgbmlib.new_voidpp(lightgbmlib.java:622) 
	at com.pdd.service.logistics.ferrari.core.model.CustomLGBMBooster.createFromModelfile(CustomLGBMBooster.java:41) 
	at com.pdd.service.logistics.ferrari.core.model.MixModelManager.loadModel(MixModelManager.java:129) 
	at com.pdd.service.logistics.ferrari.core.model.MixModelManager.init(MixModelManager.java:60) 
i use the compile "io.github.metarank:lightgbm4j:3.3.1-1" directly
how can i fix this problem

**Comment by shuttie** [comment] 2021-11-25 17:44
Have you built your own jar with maven? Or it's the jar from maven-central?

**Comment by hoffrocket** [comment] 2021-12-06 17:24
Hello,

We just encountered a similar error on OSX with version `3.3.1-1` where the root cause turned out to be that the `libomp` library was not installed.  Fixed with `brew install libomp` (you can see that done in the build process here: https://github.com/metarank/lightgbm4j/blob/3.3.1-1/.github/workflows/maven.yml)


Full error:
```
    java.lang.UnsatisfiedLinkError: 'long com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()'
        at com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp(Native Method)
        at com.microsoft.ml.lightgbm.lightgbmlib.new_voidpp(lightgbmlib.java:622)
        at io.github.metarank.lightgbm4j.LGBMBooster.loadModelFromString(LGBMBooster.java:133)

    Loading native lib osx/x86_64/lib_lightgbm.dylib
    Loading native lib /var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib
    Copied 3775632 bytes
    Extracted file: exists=true path=/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib
    Cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib: dlopen(/private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib, 1): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
      Referenced from: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib
      Reason: image not found cause: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib: dlopen(/private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib, 1): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
      Referenced from: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm6403771502418075394/lib_lightgbm.dylib
      Reason: image not found
    Loading native lib osx/x86_64/lib_lightgbm_swig.dylib
    Loading native lib /var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib
    Copied 89308 bytes
    Extracted file: exists=true path=/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib
    Cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib: dlopen(/private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib, 1): Library not loaded: @rpath/lib_lightgbm.dylib
      Referenced from: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib
      Reason: image not found cause: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib: dlopen(/private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib, 1): Library not loaded: @rpath/lib_lightgbm.dylib
      Referenced from: /private/var/folders/bp/16ymr3q102v3hf633c4g0w9w0000gn/T/lightgbm4355698126225245501/lib_lightgbm_swig.dylib
      Reason: image not found
```

**Comment by darius-sas** [comment] 2022-06-13 17:37
I was encountering a very similar issue but only while I was testing/running my app in a container.

The solution was to use a ubuntu image and install `build-essential`.

This is the Dockerfile I use
```
FROM ubuntu:22.04

RUN apt -qq update
RUN apt -qq install -y openjdk-17-jre
RUN apt -qq install -y build-essential

...
```
I'm writing this here in case anyone stumbles across this problem.

If anyone can find the exact dependencies that one needs to install on Alpine images it would be great if they can post it here.

**Comment by shuttie** [comment] 2023-01-23 13:48
Hopefully this issue can be closed with https://github.com/metarank/lightgbm4j/pull/65:
* I've added a note in readme about libomp/libgomp installation instructions
* also there's an exception handler for omp-based linking exceptions, which prints a giant banner if the libomp was not found:
![image](https://user-images.githubusercontent.com/999061/214055605-14549340-7d4d-4cdb-b6e9-8859a3ad161d.png)

**Closed by shuttie** 2023-01-23 13:48 UTC
Labels: question

**Comment by xinstein** [comment] 2024-01-11 07:36
Is there any chance I can solve this problem on spark nodes without asking the cluster manager to install libomp on all cluster nodes?

**Comment by darius-sas** [comment] 2024-01-11 15:18
> Is there any chance I can solve this problem on spark nodes without asking the cluster manager to install libomp on all cluster nodes?

If your program runs on JVM, you might be interested in reading this https://docs.oracle.com/cd/E19205-01/819-5262/aeudh/index.html
